// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDV3nJdAOKyzOEQrOCNcFxHx-lkAnKzQ',
    appId: '1:303063197791:web:589fe96c87033fe5ab53ea',
    messagingSenderId: '303063197791',
    projectId: 'agri-ai-farmersolution',
    authDomain: 'agri-ai-farmersolution.firebaseapp.com',
    storageBucket: 'agri-ai-farmersolution.firebasestorage.app',
    measurementId: 'G-6K7S0K97KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSaQsu0fHT8HUcSqukzZuQBNyVT8zl8YY',
    appId: '1:303063197791:android:f492fda5d12122b7ab53ea',
    messagingSenderId: '303063197791',
    projectId: 'agri-ai-farmersolution',
    storageBucket: 'agri-ai-farmersolution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2OX_q_XdZdULaeLqt-R_SltPM1Rboh4',
    appId: '1:303063197791:ios:2979f0c9f8c252ebab53ea',
    messagingSenderId: '303063197791',
    projectId: 'agri-ai-farmersolution',
    storageBucket: 'agri-ai-farmersolution.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy2OX_q_XdZdULaeLqt-R_SltPM1Rboh4',
    appId: '1:303063197791:ios:2979f0c9f8c252ebab53ea',
    messagingSenderId: '303063197791',
    projectId: 'agri-ai-farmersolution',
    storageBucket: 'agri-ai-farmersolution.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtDV3nJdAOKyzOEQrOCNcFxHx-lkAnKzQ',
    appId: '1:303063197791:web:492e555a59ba7b69ab53ea',
    messagingSenderId: '303063197791',
    projectId: 'agri-ai-farmersolution',
    authDomain: 'agri-ai-farmersolution.firebaseapp.com',
    storageBucket: 'agri-ai-farmersolution.firebasestorage.app',
    measurementId: 'G-DT0GG8YCPG',
  );
}
